using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * */

namespace Euler2
{
    class Program
    {
        static void Main(string[] args)
        {
            int a = 1;
            int b = 1;
            int hold; //extra memory spot to swap around these items
            int sum = 0;
            while (b < 4000000)
            {
                hold = b;
                b = a + b;
                a = hold;
                if (b % 2 == 0)
                    sum += b;
            }

            Console.WriteLine(sum);
        }
    }
}
